[project]
name = "api-lambda"
version = "0.1.0"
description = "ManyMetrics API Lambda"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.97",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
